# Generated by Django 5.0.3 on 2024-04-15 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.inventorymodel')),
            ],
            options={
                'db_table': 'inventory_items',
            },
        ),
    ]
